/home/kasm920/binance1-pro/logs/main.log
/home/kasm920/binance1-pro/logs/system.log
/home/kasm920/binance1-pro/logs/error.log
/home/kasm920/binance1-pro/logs/trades.log
/home/kasm920/binance1-pro/logs/orch/*.log {
    daily
    rotate 7
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
    dateext
    dateformat -%Y%m%d
    maxsize 50M
    su kasm920 kasm920
}
